(define (problem user-study-1)
(:domain transport-strips)

(:objects
postoffice supermarket taylor cafe bank lopez jones smith packingstation - location
t1 t2 - truck
p0 p1 p2 p3 p4 - package
    level13 level12 level11 level10 level9 level8 level7 level6 level5 level4 level3 level2 level1 level0 - fuellevel
)

(:init
(sum level0 level0 level0)
(sum level0 level1 level1)
(sum level0 level2 level2)
(sum level0 level3 level3)
(sum level0 level4 level4)
(sum level0 level5 level5)
(sum level0 level6 level6)
(sum level0 level7 level7)
(sum level0 level8 level8)
(sum level0 level9 level9)
(sum level0 level10 level10)
(sum level0 level11 level11)
(sum level0 level12 level12)
(sum level0 level13 level13)
(sum level1 level0 level1)
(sum level1 level1 level2)
(sum level1 level2 level3)
(sum level1 level3 level4)
(sum level1 level4 level5)
(sum level1 level5 level6)
(sum level1 level6 level7)
(sum level1 level7 level8)
(sum level1 level8 level9)
(sum level1 level9 level10)
(sum level1 level10 level11)
(sum level1 level11 level12)
(sum level1 level12 level13)
(sum level2 level0 level2)
(sum level2 level1 level3)
(sum level2 level2 level4)
(sum level2 level3 level5)
(sum level2 level4 level6)
(sum level2 level5 level7)
(sum level2 level6 level8)
(sum level2 level7 level9)
(sum level2 level8 level10)
(sum level2 level9 level11)
(sum level2 level10 level12)
(sum level2 level11 level13)
(sum level3 level0 level3)
(sum level3 level1 level4)
(sum level3 level2 level5)
(sum level3 level3 level6)
(sum level3 level4 level7)
(sum level3 level5 level8)
(sum level3 level6 level9)
(sum level3 level7 level10)
(sum level3 level8 level11)
(sum level3 level9 level12)
(sum level3 level10 level13)
(sum level4 level0 level4)
(sum level4 level1 level5)
(sum level4 level2 level6)
(sum level4 level3 level7)
(sum level4 level4 level8)
(sum level4 level5 level9)
(sum level4 level6 level10)
(sum level4 level7 level11)
(sum level4 level8 level12)
(sum level4 level9 level13)
(sum level5 level0 level5)
(sum level5 level1 level6)
(sum level5 level2 level7)
(sum level5 level3 level8)
(sum level5 level4 level9)
(sum level5 level5 level10)
(sum level5 level6 level11)
(sum level5 level7 level12)
(sum level5 level8 level13)
(sum level6 level0 level6)
(sum level6 level1 level7)
(sum level6 level2 level8)
(sum level6 level3 level9)
(sum level6 level4 level10)
(sum level6 level5 level11)
(sum level6 level6 level12)
(sum level6 level7 level13)
(sum level7 level0 level7)
(sum level7 level1 level8)
(sum level7 level2 level9)
(sum level7 level3 level10)
(sum level7 level4 level11)
(sum level7 level5 level12)
(sum level7 level6 level13)
(sum level8 level0 level8)
(sum level8 level1 level9)
(sum level8 level2 level10)
(sum level8 level3 level11)
(sum level8 level4 level12)
(sum level8 level5 level13)
(sum level9 level0 level9)
(sum level9 level1 level10)
(sum level9 level2 level11)
(sum level9 level3 level12)
(sum level9 level4 level13)
(sum level10 level0 level10)
(sum level10 level1 level11)
(sum level10 level2 level12)
(sum level10 level3 level13)
(sum level11 level0 level11)
(sum level11 level1 level12)
(sum level11 level2 level13)
(sum level12 level0 level12)
(sum level12 level1 level13)
(sum level13 level0 level13)

(connected postoffice supermarket)
(fuelcost level3 postoffice supermarket)
(connected supermarket postoffice)
(fuelcost level3 supermarket postoffice)

(connected postoffice cafe)
(fuelcost level2 postoffice cafe)
(connected cafe postoffice)
(fuelcost level2 cafe postoffice)

(connected taylor supermarket)
(fuelcost level1 taylor supermarket)
(connected supermarket taylor)
(fuelcost level1 supermarket taylor)

(connected bank supermarket)
(fuelcost level2 bank supermarket)
(connected supermarket bank)
(fuelcost level2 supermarket bank)

(connected taylor lopez)
(fuelcost level3 taylor lopez)
(connected lopez taylor)
(fuelcost level3 lopez taylor)

(connected bank cafe)
(fuelcost level2 bank cafe)
(connected cafe bank)
(fuelcost level2 cafe bank)

(connected jones cafe)
(fuelcost level1 jones cafe)
(connected cafe jones)
(fuelcost level1 cafe jones)

(connected bank lopez)
(fuelcost level1 bank lopez)
(connected lopez bank)
(fuelcost level1 lopez bank)

(connected bank smith)
(fuelcost level3 bank smith)
(connected smith bank)
(fuelcost level3 smith bank)

(connected packingstation lopez)
(fuelcost level2 packingstation lopez)
(connected lopez packingstation)
(fuelcost level2 lopez packingstation)

(connected jones smith)
(fuelcost level3 jones smith)
(connected smith jones)
(fuelcost level3 smith jones)

(connected packingstation smith)
(fuelcost level2 packingstation smith)
(connected smith packingstation)
(fuelcost level2 smith packingstation)


(at t1 cafe)
(empty t1)
(fuel t1 level10)
(at t2 packingstation)
(empty t2)
(fuel t2 level12)

(at p0 postoffice)
(at p1 postoffice)
(at p2 packingstation)
(at p3 packingstation)
(at p4 bank)
)

(:goal
(and
(at p0 lopez)
(at p1 smith)
(at p2 jones)
(at p3 taylor)
(at p4 postoffice)
)
)
)
